### ISSUE TITLE
Fix versioning to be accepted into the Rack community repository

### ISSUE THREAD

**Issue by AndrewBelt** [adbrant/ArableInstruments#10]
Rack v0.5.1 will include a plugin manager, and plugins need to follow the [versioning guidelines](https://github.com/VCVRack/Rack/issues/266) in order to be accepted. You can use this [example plugin Makefile](https://github.com/VCVRack/Tutorial/blob/master/Makefile) and [Tutorial.cpp file](https://github.com/VCVRack/Tutorial/blob/master/src/Tutorial.cpp) as a reference for making sure the version is the same in the C++, Makefile, and JSON manifest.

- Please remove the `v` from the version string in the C++ file.

Once you've fixed this, send a PR to the [Rack community repository](https://github.com/VCVRack/community) and remove the `"disabled"` property in the JSON manifest file if present.

**Comment by cschol** [comment]
This is not an issue anymore.
