### ISSUE TITLE
Put ParableInstruments onto separate branch

### ISSUE THREAD

**Issue by cschol** [adbrant/ArableInstruments#12]
@adbrant The code for `ParableInstruments` needs to be put on a separate branch, i.e. it needs to be buildable with a simple `make`.

This is required for integration into the community build system. Right now, the plugin requires special handling in using the separate `Makefile` to build.

Thank you!

**Comment by adbrant** [comment]
I've made the branch 'parable' which will build the parasites code with a simple make.
I've tested both versions with an up to date Rack repo and they seem to work, let me know if there's anything else I should do before the 0.6 release.

**Comment by cschol** [comment]
Thank you! I will try it out and let you know.
