### ISSUE TITLE
Update VERSION in Makefile

### ISSUE THREAD

**Issue by cschol** [adbrant/ArableInstruments#13]
`VERSION` in the `Makefile` needs to be updated to `0.6.0` to remove the `dev` suffix (for both Arable and Parable).

**Comment by cschol** [comment]
Ping.

**Comment by adbrant** [comment]
Sorry about the delay, updated now. I've also added you as a collaborator if you want to update anything directly.

**Comment by cschol** [comment]
Great. Thanks!

**Comment by cschol** [comment]
This is fixed.
