### ISSUE TITLE
No separate slug for ParableInstruments?

### ISSUE THREAD

**Issue by cschol** [adbrant/ArableInstruments#14]
The `src/Clouds.cpp` file does not have a separate slug for `ParableInstruments`. Is this intentional?

**Comment by adbrant** [comment]
I think I did this so both would appear under the same menu (so less clutter for the user).
If this causes any issues it could be changed.

**Comment by cschol** [comment]
Not sure it causes issues by itself, but it **will** break existing patches. Just figured I'd point it out.

**Comment by cschol** [comment]
Separate slug was implemented for Rack `v1` port to prevent confusion in plugin manager.
