### ISSUE TITLE
Vcv 1.0 update?

### ISSUE THREAD

**Issue by killiun** [adbrant/ArableInstruments#15]
Hello any plans to update for version 1.0?

**Comment by gilbertohasnofb** [comment]
Yes, that would be great. At the moment version VCV 1.x does not see any of the Arable Instrument modules.

**Comment by cschol** [comment]
Working on it.

**Comment by adbrant** [comment]
Hi, sorry I haven't had much bandwidth to look at updating these to the latest version yet. I would be happy to take a pull request and test it out though :)

**Comment by cschol** [comment]
@adbrant You gave me access to the repo some time ago. I'll push a `v1` branch up here tonight.

**Comment by cschol** [comment]
@adbrant Branches uploaded: `v1` and `parables-v1`.

Give it a test and if it works we can merge to `master` and `parable` and I will integrate it in the Plugin Manager.

**Comment by adbrant** [comment]
Thanks for the update, I gave it a try on my system  (windows 10) and it is working well. I've merged the changes to master and parable.

**Comment by cschol** [comment]
Cool! 

#16 is strange (probably related to a very recent `g++` version), but it compiles fine on my integration machine with a `mingw32` cross-compile. That is what the official build system uses also.

I would not say that that should hold up the release in the Plugin Manager.

**Comment by gilbertohasnofb** [comment]
Any news about a possible v1.0 release?

**Comment by killiun** [comment]
Yeah I’m really missing it in my patches.

**Comment by cschol** [comment]
Integration complete.

https://github.com/VCVRack/library/issues/594
https://github.com/VCVRack/library/issues/595

**Comment by adbrant** [comment]
Great, thank you!
