### ISSUE TITLE
Compile error Win 10 [parable-v1 branch]

### ISSUE THREAD

**Issue by SteveRussell33** [adbrant/ArableInstruments#16]
`g++ -std=c++11 -Wsuggest-override -DTEST -DPARASITES -I./parasites -Wno-unused-local-typedefs -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/parasites/clouds/dsp/granular_processor.cc.o parasites/clouds/dsp/granular_processor.cc
parasites/clouds/dsp/granular_processor.cc: In member function 'void clouds::GranularProcessor::ProcessGranular(clouds::FloatFrame*, clouds::FloatFrame*, size_t)':
parasites/clouds/dsp/granular_processor.cc:181:9: error: narrowing conversion of '0.0f' from 'float' to 'bool' [-Wnarrowing]
  181 |         };
      |         ^
parasites/clouds/dsp/granular_processor.cc:181:9: error: narrowing conversion of '0.0f' from 'float' to 'bool' [-Wnarrowing]
parasites/clouds/dsp/granular_processor.cc:181:9: warning: missing initializer for member 'clouds::Parameters::granular' [-Wmissing-field-initializers]
parasites/clouds/dsp/granular_processor.cc:181:9: warning: missing initializer for member 'clouds::Parameters::spectral' [-Wmissing-field-initializers]
make: *** [../../compile.mk:66: build/parasites/clouds/dsp/granular_processor.cc.o] Error 1`

**Comment by cschol** [comment]
What compiler version are you using?

**Comment by SteveRussell33** [comment]
Msys2 g++ v9.1.0

**Comment by SteveRussell33** [comment]
Cloned a new local repo - works.
