### ISSUE TITLE
Update to v2

### ISSUE THREAD

**Issue by cschol** [adbrant/ArableInstruments#17]
Hey @adbrant, are you OK with me updating this plugin to `v2` of Rack?

I also would like to change the license to `GPLv3` at this time to align with the overall license update of Rack, if you are OK with that.

Thanks.

**Comment by adbrant** [comment]
Yes that is OK with me. Feel free to raise a PR.

**Comment by cschol** [comment]
Code pushed to `v2` and `parable-v2` branches. You gave me push access last time for the `v1` update.

If it looks good to you, you can merge it to `master` and `parable` (or I can).

Afterwards, I will move it to integration for the Rack Library.

**Comment by adbrant** [comment]
I've merged those branches into the master/parable, thanks!

**Comment by cschol** [comment]
Cool. I'll put them in the integration queue. Thanks!
