### ISSUE TITLE
Compile fails in Mint64

### ISSUE THREAD

**Issue by asbaklm** [adbrant/ArableInstruments#5]
In file included from src/AudibleInstruments.cpp:1:0:
src/AudibleInstruments.hpp:15:8: warning: ‘virtual rack::Menu* BraidsWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
src/AudibleInstruments.hpp:20:8: warning: ‘virtual rack::Menu* ElementsWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
src/AudibleInstruments.hpp:77:8: warning: ‘virtual rack::Menu* FramesWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
src/AudibleInstruments.cpp: In function ‘void init(rack::Plugin*)’:
src/AudibleInstruments.cpp:16:10: error: ‘struct rack::Plugin’ has no member named ‘name’
  plugin->name = "Arable Instruments";
          ^
src/AudibleInstruments.cpp:17:10: error: ‘struct rack::Plugin’ has no member named ‘homepageUrl’
  plugin->homepageUrl = "https://github.com/adbrant/ArableInstruments";
          ^
src/AudibleInstruments.cpp:19:72: error: no matching function for call to ‘createModel(rack::Plugin*&, const char [5], const char [27])’
  createModel<CloudsWidget>(plugin, "Joni", "Joni - Texture Synthesizer");
                                                                        ^
In file included from src/AudibleInstruments.hpp:1:0,
                 from src/AudibleInstruments.cpp:1:
../../include/rack.hpp:22:8: note: candidate: template<class TModuleWidget, class ... Tags> rack::Model* rack::createModel(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, Tags ...)
 Model *createModel(std::string manufacturer, std::string slug, std::string name, Tags... tags) {
        ^
../../include/rack.hpp:22:8: note:   template argument deduction/substitution failed:
src/AudibleInstruments.cpp:19:72: note:   cannot convert ‘plugin’ (type ‘rack::Plugin*’) to type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
  createModel<CloudsWidget>(plugin, "Joni", "Joni - Texture Synthesizer");
                                                                        ^
In file included from src/Clouds.cpp:2:0:
src/AudibleInstruments.hpp:15:8: warning: ‘virtual rack::Menu* BraidsWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
src/AudibleInstruments.hpp:20:8: warning: ‘virtual rack::Menu* ElementsWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
src/AudibleInstruments.hpp:77:8: warning: ‘virtual rack::Menu* FramesWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^
../../compile.mk:53: recipe for target 'build/src/AudibleInstruments.cpp.o' failed
make: *** [build/src/AudibleInstruments.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
src/Clouds.cpp:77:8: warning: ‘virtual void Clouds::step()’ can be marked override [-Wsuggest-override]
   void step();
        ^
src/Clouds.cpp: In member function ‘virtual void Clouds::step()’:
src/Clouds.cpp:166:35: error: ‘gSampleRate’ was not declared in this scope
       inputSrc.setRatio(32000.0 / gSampleRate);
                                   ^
src/Clouds.cpp:242:26: error: ‘gSampleRate’ was not declared in this scope
       outputSrc.setRatio(gSampleRate / 32000.0);
                          ^
src/Clouds.cpp: In constructor ‘CloudsWidget::CloudsWidget()’:
src/Clouds.cpp:320:12: error: ‘createValueLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(68+5, 52+4), &module->freezeLight));
            ^
src/Clouds.cpp:320:40: error: ‘GreenValueLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(68+5, 52+4), &module->freezeLight));
                                        ^
src/Clouds.cpp:320:40: error: template argument 1 is invalid
src/Clouds.cpp: At global scope:
src/Clouds.cpp:333:8: error: ‘void CloudsModeItem::onAction()’ marked ‘override’, but does not override
   void onAction() override {
        ^
src/Clouds.cpp:346:8: error: ‘void CloudsMonoItem::onAction()’ marked ‘override’, but does not override
   void onAction() override {
        ^
src/Clouds.cpp:359:8: error: ‘void CloudsLofiItem::onAction()’ marked ‘override’, but does not override
   void onAction() override {
        ^
src/Clouds.cpp:372:8: error: ‘void CloudsBufferItem::onAction()’ marked ‘override’, but does not override
   void onAction() override {
        ^
src/Clouds.cpp: In member function ‘virtual rack::Menu* CloudsWidget::createContextMenu()’:
src/Clouds.cpp:387:41: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<MenuLabel>());
                                         ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:388:65: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<MenuLabel>(&MenuEntry::text, "MODE"));
                                                                 ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:389:162: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsModeItem>(&MenuEntry::text, "GRANULAR", &CloudsModeItem::clouds, clouds, &CloudsModeItem::mode, clouds::PLAYBACK_MODE_GRANULAR));
                                                                                                                                                                  ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:390:162: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsModeItem>(&MenuEntry::text, "SPECTRAL", &CloudsModeItem::clouds, clouds, &CloudsModeItem::mode, clouds::PLAYBACK_MODE_SPECTRAL));
                                                                                                                                                                  ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:391:172: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsModeItem>(&MenuEntry::text, "LOOPING_DELAY", &CloudsModeItem::clouds, clouds, &CloudsModeItem::mode, clouds::PLAYBACK_MODE_LOOPING_DELAY));
                                                                                                                                                                            ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:392:160: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsModeItem>(&MenuEntry::text, "STRETCH", &CloudsModeItem::clouds, clouds, &CloudsModeItem::mode, clouds::PLAYBACK_MODE_STRETCH));
                                                                                                                                                                ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:397:72: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<MenuLabel>(&MenuEntry::text, "STEREO/MONO"));
                                                                        ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:398:138: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsMonoItem>(&MenuEntry::text, "STEREO", &CloudsMonoItem::clouds, clouds, &CloudsMonoItem::setting, false));
                                                                                                                                          ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:399:135: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsMonoItem>(&MenuEntry::text, "MONO", &CloudsMonoItem::clouds, clouds, &CloudsMonoItem::setting, true));  
                                                                                                                                       ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:401:70: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<MenuLabel>(&MenuEntry::text, "HIFI/LOFI"));
                                                                      ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:402:136: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsLofiItem>(&MenuEntry::text, "HIFI", &CloudsLofiItem::clouds, clouds, &CloudsLofiItem::setting, false));
                                                                                                                                        ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
src/Clouds.cpp:403:135: warning: ‘void rack::Menu::pushChild(rack::Widget*)’ is deprecated [-Wdeprecated-declarations]
   menu->pushChild(construct<CloudsLofiItem>(&MenuEntry::text, "LOFI", &CloudsLofiItem::clouds, clouds, &CloudsLofiItem::setting, true));  
                                                                                                                                       ^
In file included from ../../include/app.hpp:4:0,
                 from ../../include/gui.hpp:2,
                 from ../../include/rack.hpp:8,
                 from src/AudibleInstruments.hpp:1,
                 from src/Clouds.cpp:2:
../../include/widgets.hpp:315:7: note: declared here
  void pushChild(Widget *child) DEPRECATED {
       ^
../../compile.mk:53: recipe for target 'build/src/Clouds.cpp.o' failed
make: *** [build/src/Clouds.cpp.o] Error 1

**Comment by adbrant** [comment]
I think this is due to the plugins being compatible with v0.4.0 instead of v0.50 at the time.
I've updated the plugins to work with v0.5.0 now so it could work.

**Comment by asbaklm** [comment]
Confirm it now works for latest dev master (0.5) , thank you very much! =)
